### Get the Jupyter Server version
GET http://jupyter:5000/healthcheck HTTP/1.1
content-type: application/json

###

POST http://jupyter:5000/run-notebook HTTP/1.1
content-type: application/json

{
	"notebook_name": "test.ipynb",
  "parameters": {
    "param1": "value1",
    "param2": "value2"
	}
}