### Get the Jupyter Server version
GET http://jupyter:8888/api HTTP/1.1
content-type: application/json

### Get contents of a file

GET http://jupyter:8888/api/contents/mapbox.ipynb HTTP/1.1
content-type: application/json

### Get contents of a directory

GET http://jupyter:8888/api/contents/ HTTP/1.1
content-type: application/json