# assume roles
ecr-sensand-plugin: &ecr-sensand
  ecr#v2.7.0:
    login: true
    account-ids: "622020772926" # AWS Platform account
    region: us-east-1
    assume_role:
      role_arn: arn:aws:iam::622020772926:role/BuildkiteEcrPushPullRole

assume-role-staging-plugin: &assume-role-staging
  cultureamp/aws-assume-role#v0.1.0:
    role: "arn:aws:iam::005168020145:role/BuildkiteRole"

# plugins
docker-compose-deploy-plugin: &docker-compose-deploy
  docker-compose#v4.15.0:
    run: deploy
    config:
      - .buildkite/docker/docker-compose.deploy.yaml
    volumes:
      - "./:/buildkite"
    env:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - IMAGE_NAME
      - IMAGE_URL

steps:
  # TODO: lint & test
  - group: "Notebook Executor Deploy (Staging)"
    key: "notebook-executor-deploy"
    steps:

      # - label: "echo"
      #   command:
      #     - echo build.pull_request.draft
      #     - echo $build.pull_request.draft

      # - label: "same line check"
      #   command:
      #     - echo "test"
      #   if: "$BUILDKITE_PULL_REQUEST == false && build.pull_request.draft == null"

      - label: "diff lines"
        command:
          - echo "test"
        if: |
          build.branch == "main" ||
          (build.pull_request.id == null &&
          build.pull_request.draft == null)
          