# assume roles
ecr-sensand-plugin: &ecr-sensand
  ecr#v2.7.0:
    login: true
    account-ids: "622020772926" # AWS Platform account
    region: us-east-1
    assume_role:
      role_arn: arn:aws:iam::622020772926:role/BuildkiteEcrPushPullRole

assume-role-staging-plugin: &assume-role-staging
  cultureamp/aws-assume-role#v0.1.0:
    role: "arn:aws:iam::005168020145:role/BuildkiteRole"

# plugins
docker-compose-deploy-plugin: &docker-compose-deploy
  docker-compose#v4.15.0:
    run: deploy
    config:
      - .buildkite/docker/docker-compose.deploy.yaml
    volumes:
      - "./:/buildkite"
    env:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - IMAGE_NAME

steps:
  # TODO: lint & test
  - group: "Notebook Executor Deploy (Staging)"
    key: "notebook-executor-deploy"
    steps:
      - label: "[TEST STEP]"
        command:
          - echo "This should only run when this branch has an open PR"
        if: "build.pull_request.draft != null" # only run on open PR (NOT FULLY TESTED)
        
      # - label: ":docker: Notebook Executor Build & Push"
      #   plugins:
      #     - docker-compose#v4.14.0:
      #         build: notebook-executor
      #         image-repository: 622020772926.dkr.ecr.us-east-1.amazonaws.com/notebook-executor
      #         image-name: latest #"${BUILDKITE_BRANCH}-${BUILDKITE_COMMIT}"
      #         cache-from:
      #           - notebook-executor:622020772926.dkr.ecr.us-east-1.amazonaws.com/notebook-executor:latest
      #         config:
      #           - docker-compose.yml
      #     - *ecr-sensand
        
      # TODO: update lambda
      - label: ":aws: Update Notebook Executor Lambda (Staging)"
        env:
          IMAGE_NAME: test-name
        command:
          #- echo $$IMAGE_NAME
          #- which aws
          - aws ecs list-clusters
          - aws s3 ls
          - aws lambda get-function --function-name NotebookExecutorFunction
          # - ./buildkite/.buildkite/ecs-deploy.sh -c blockbase -n api -i $$IMAGE_NAME --enable-rollback
        #retry: *auto-retries
        #concurrency: 1
        #concurrency_group: "staging-backend/deploy"
        plugins:
          - *assume-role-staging
          - *docker-compose-deploy