# assume roles
ecr-sensand-plugin: &ecr-sensand
  ecr#v2.7.0:
    login: true
    account-ids: "622020772926" # AWS Platform account
    region: us-east-1
    assume_role:
      role_arn: arn:aws:iam::622020772926:role/BuildkiteEcrPushPullRole

assume-role-staging-plugin: &assume-role-staging
  cultureamp/aws-assume-role#v0.1.0:
    role: "arn:aws:iam::005168020145:role/BuildkiteRole"

assume-role-production-plugin: &assume-role-production
  cultureamp/aws-assume-role#v0.1.0:
    role: "arn:aws:iam::914193799137:role/BuildkiteRole"

# plugins
docker-compose-deploy-plugin: &docker-compose-deploy
  docker-compose#v4.15.0:
    run: deploy
    config:
      - .buildkite/docker/docker-compose.deploy.yaml
    volumes:
      - "./:/buildkite"
    env:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - IMAGE_NAME
      - IMAGE_URL

steps:
  # TODO: lint & test
  - group: "Notebook Executor Deploy"
    key: "notebook-executor-deploy"
    steps:

      - label: "TEST"
        command:
          - echo ${BUILDKITE_PULL_REQUEST_DRAFT}

      # - label: "CONDITIONAL TEST"
      #   command:
      #     - echo "cond test"
      #   if: "$BUILDKITE_PULL_REQUEST"

      # - label: ":docker: Notebook Executor Build & Push (Platform)"
      #   key: "notebook-executor-build-and-push"
      #   plugins:
      #     - docker-compose#v4.14.0:
      #         build: notebook-executor
      #         image-repository: 622020772926.dkr.ecr.us-east-1.amazonaws.com/notebook-executor
      #         image-name: "${BUILDKITE_BRANCH}-${BUILDKITE_COMMIT}"
      #         cache-from:
      #           - notebook-executor:622020772926.dkr.ecr.us-east-1.amazonaws.com/notebook-executor:${BUILDKITE_BRANCH}-${BUILDKITE_COMMIT}
      #           - notebook-executor:622020772926.dkr.ecr.us-east-1.amazonaws.com/notebook-executor:latest
      #         config:
      #           - docker-compose.yml
      #     - *ecr-sensand
      #   if: "$BUILDKITE_PULL_REQUEST"

      # - block: "Deploy Staging (Manual)"
      #   prompt: "Update Lambda Function in Staging?"
      #   key: "deploy-staging-manual"
      #   depends_on:
      #     - "notebook-executor-build-and-push"

      # - label: ":aws: Update Notebook Executor Lambda (Staging)"
      #   branches: main
      #   env:
      #     IMAGE_NAME: notebook-executor
      #     IMAGE_URL: 622020772926.dkr.ecr.us-east-1.amazonaws.com
      #   command:
      #     - aws lambda update-function-code --function-name NotebookExecutorFunction --image-uri $$IMAGE_URL/$$IMAGE_NAME:${BUILDKITE_BRANCH}-${BUILDKITE_COMMIT} --region us-east-1
      #   depends_on:
      #     - "deploy-staging-manual"
      #   plugins:
      #     - *assume-role-staging
      #     - *docker-compose-deploy
      
      # - block: "Deploy Production (Manual)"
      #   prompt: "Update Lambda Function in Production?"
      #   key: "deploy-production-manual"
      #   depends_on:
      #     - "notebook-executor-build-and-push"

      # - label: ":aws: Update Notebook Executor Lambda (Production)"
      #   branches: main
      #   env:
      #     IMAGE_NAME: notebook-executor
      #     IMAGE_URL: 622020772926.dkr.ecr.us-east-1.amazonaws.com
      #   command:
      #     - aws lambda update-function-code --function-name NotebookExecutorFunction --image-uri $$IMAGE_URL/$$IMAGE_NAME:${BUILDKITE_BRANCH}-${BUILDKITE_COMMIT} --region us-east-1
      #   depends_on:
      #     - "deploy-production-manual"
      #   plugins:
      #     - *assume-role-production
      #     - *docker-compose-deploy
          