# assume roles
ecr-sensand-plugin: &ecr-sensand
  ecr#v2.7.0:
    login: true
    account-ids: "622020772926" # AWS Platform account
    region: us-east-1
    assume_role:
      role_arn: arn:aws:iam::622020772926:role/BuildkiteEcrPushPullRole

assume-role-staging-plugin: &assume-role-staging
  cultureamp/aws-assume-role#v0.1.0:
    role: "arn:aws:iam::005168020145:role/BuildkiteRole"

assume-role-production-plugin: &assume-role-production
  cultureamp/aws-assume-role#v0.1.0:
    role: "arn:aws:iam::914193799137:role/BuildkiteRole"

# plugins
docker-compose-deploy-plugin: &docker-compose-deploy
  docker-compose#v4.15.0:
    run: deploy
    config:
      - .buildkite/docker/docker-compose.deploy.yaml
    volumes:
      - "./:/buildkite"
    env:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - IMAGE_NAME
      - IMAGE_URL

steps:
  - group: "Pytest Unit Tests"
    key: "pytest-unit-tests"
    steps:
      - label: ":pytest: Run pytest"
        key: "run-pytest"
        plugins:
          - docker-compose#v4.15.0:
              run: pytest
              config: docker-compose.pytest.yaml
          - *ecr-sensand
        if: build.message !~ /skippy/

  - wait

  - group: "Notebook Executor Deploy"
    key: "notebook-executor-deploy"
    steps:
      - label: ":docker: Notebook Executor Build & Push"
        key: "notebook-executor-build-and-push"
        plugins:
          - docker-compose#v4.14.0:
              build: notebook-executor
              image-repository: 622020772926.dkr.ecr.us-east-1.amazonaws.com/notebook-executor
              image-name: "${BUILDKITE_BRANCH_SLUG}-${BUILDKITE_COMMIT}"
              cache-from:
                - notebook-executor:622020772926.dkr.ecr.us-east-1.amazonaws.com/notebook-executor:${BUILDKITE_BRANCH_SLUG}-${BUILDKITE_COMMIT}
                - notebook-executor:622020772926.dkr.ecr.us-east-1.amazonaws.com/notebook-executor:latest
              config:
                - docker-compose.yml
          - *ecr-sensand
        if: |
          build.branch == "main" || (build.pull_request.id != null && !build.pull_request.draft)

      - label: ":docker: Notebook Executor Build & Push (latest)"
        key: "notebook-executor-build-and-push-latest"
        plugins:
          - docker-compose#v4.14.0:
              build: notebook-executor
              image-repository: 622020772926.dkr.ecr.us-east-1.amazonaws.com/notebook-executor
              image-name: latest
              cache-from:
                - notebook-executor:622020772926.dkr.ecr.us-east-1.amazonaws.com/notebook-executor:${BUILDKITE_BRANCH_SLUG}-${BUILDKITE_COMMIT}
                - notebook-executor:622020772926.dkr.ecr.us-east-1.amazonaws.com/notebook-executor:latest
              config:
                - docker-compose.yml
          - *ecr-sensand
        if: |
          build.branch == "main" || (build.pull_request.id != null && !build.pull_request.draft)

      - block: "Deploy Staging (Manual)"
        prompt: "Update Lambda Function in Staging?"
        key: "deploy-staging-manual"
        depends_on:
          - "notebook-executor-build-and-push"
        if: |
          build.branch == "main" || (build.pull_request.id != null && !build.pull_request.draft)

      - label: ":aws: Update Notebook Executor Lambda (Staging)"
        env:
          IMAGE_NAME: notebook-executor
          IMAGE_URL: 622020772926.dkr.ecr.us-east-1.amazonaws.com
        command:
          - aws lambda update-function-code --function-name NotebookExecutorFunction --image-uri $$IMAGE_URL/$$IMAGE_NAME:${BUILDKITE_BRANCH_SLUG}-${BUILDKITE_COMMIT} --region us-east-1
        depends_on:
          - "deploy-staging-manual"
        plugins:
          - *assume-role-staging
          - *docker-compose-deploy
        if: |
          build.branch == "main" || (build.pull_request.id != null && !build.pull_request.draft)

      - block: "Deploy Production (Manual)"
        prompt: "Update Lambda Function in Production?"
        branches: main
        key: "deploy-production-manual"
        depends_on:
          - "notebook-executor-build-and-push"

      - label: ":aws: Update Notebook Executor Lambda (Production)"
        branches: main
        env:
          IMAGE_NAME: notebook-executor
          IMAGE_URL: 622020772926.dkr.ecr.us-east-1.amazonaws.com
        command:
          - aws lambda update-function-code --function-name NotebookExecutorFunction --image-uri $$IMAGE_URL/$$IMAGE_NAME:${BUILDKITE_BRANCH_SLUG}-${BUILDKITE_COMMIT} --region us-east-1
        depends_on:
          - "deploy-production-manual"
        plugins:
          - *assume-role-production
          - *docker-compose-deploy

  - group: "GIS Base Image"
    key: "gis-base-image"
    steps:
      - block: "Push Base Image (Manual)"
        prompt: "Push Base Image to Platform ECR?"
        key: "push-base-image-manual"

      - label: ":docker: GIS Base Build & Push"
        key: "gis-base-build-and-push"
        plugins:
          - docker-compose#v4.14.0:
              build: gis-base
              image-repository: 622020772926.dkr.ecr.us-east-1.amazonaws.com/gis-base
              image-name: latest
              cache-from:
                - gis-base:622020772926.dkr.ecr.us-east-1.amazonaws.com/gis-base:latest
              config:
                - docker-compose.base.yaml
          - *ecr-sensand
        
        
