# assume roles
ecr-sensand-plugin: &ecr-sensand
  ecr#v2.7.0:
    login: true
    account-ids: "622020772926" # AWS Platform account
    region: us-east-1
    assume_role:
      role_arn: arn:aws:iam::622020772926:role/BuildkiteEcrPushPullRole

assume-role-staging-plugin: &assume-role-staging
  cultureamp/aws-assume-role#v0.1.0:
    role: "arn:aws:iam::005168020145:role/BuildkiteRole"

# plugins
docker-compose-deploy-plugin: &docker-compose-deploy
  docker-compose#v4.15.0:
    run: deploy
    config:
      - .buildkite/docker/docker-compose.deploy.yaml
    volumes:
      - "./:/buildkite"
    env:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - IMAGE_NAME
      - IMAGE_URL

steps:
  # TODO: lint & test
  - group: "Notebook Executor Deploy (Staging)"
    key: "notebook-executor-deploy"
    steps:
      # - label: "[TEST STEP]"
      #   command:
      #     - echo "This should only run when this branch has an open PR"
        
      # - label: ":docker: Notebook Executor Build & Push"
      #   plugins:
      #     - docker-compose#v4.14.0:
      #         build: notebook-executor
      #         image-repository: 622020772926.dkr.ecr.us-east-1.amazonaws.com/notebook-executor
      #         image-name: latest # TODO: change image tag "${BUILDKITE_BRANCH}-${BUILDKITE_COMMIT}"
      #         cache-from:
      #           - notebook-executor:622020772926.dkr.ecr.us-east-1.amazonaws.com/notebook-executor:latest
      #         config:
      #           - docker-compose.yml
      #     - *ecr-sensand
        
      - label: ":aws: Update Notebook Executor Lambda (Staging)"
        env:
          IMAGE_NAME: notebook-executor
          IMAGE_URL: 622020772926.dkr.ecr.us-east-1.amazonaws.com
        command:
          - aws lambda update-function-code --function-name NotebookExecutorFunction --image-uri $$IMAGE_URL/$$IMAGE_NAME:latest --region us-east-1
        #retry: *auto-retries
        #concurrency: 1
        #concurrency_group: "staging-backend/deploy"
        plugins:
          - *assume-role-staging
          - *docker-compose-deploy
          